# Site settings
title: dont-miss-list
name: Don't Miss List
description: >
  Once a month, we’ll be sending you a hand-picked selection of days out and experiences, plus unmissable deals on flights and getaways. Whatever your interests – West End theatre, cruise breaks or helicopter tours – we’ll be helping you make the most of your summer, come rain or sunshine. Welcome to the very first edition – we hope you enjoy it!
baseurl: "/dont-miss-list" # the subpath of your site, e.g. /blog/
url: "https://www.secretescapes.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, bower_components, bower.json, README.md]


defaults:
  -
    scope:
      path: "2016"
    values:
      layout: "landing-page"
  -
    scope:
      path: "2017"
    values:
      layout: "landing-page"